"use client";
import { useState } from "react";
import { followupOutcomes } from "@/lib/crm/followup";
import { ListChecks, MessageCircle, Pencil, Phone, Plus } from "lucide-react";
import { appointmentStatuses, displayDate, sources, stages, type ContactDetail, type CRMRecord, type Entity, type TeamMember } from "@/lib/crm/types";

export function ContactProfile({detail,staff,onEdit,onAdd}:{detail:ContactDetail;staff:TeamMember[];onEdit:(entity:Entity,r:CRMRecord)=>void;onAdd:(entity:Entity,r:Partial<CRMRecord>)=>void}) {
 const [tab,setTab]=useState("records");const [now]=useState(()=>Date.now());const {contact,stats,nextTask}=detail;
 const preset={contact_id:contact.id,contact_name:contact.name,source:contact.source};
 const owner=(key?:string)=>staff.find(s=>s.username===key)?.display_name||key||"غير معيّن";
 const labels:Record<string,string>={contacts:"بيانات التواصل",inquiries:"طلب حجز",appointments:"موعد",tasks:"متابعة"};
 const actions:Record<string,string>={create:"إضافة",update:"تعديل",booking_sync:"تحديث الطلب من الموعد",appointment_link:"ربط الموعد بطلبه",followup_result:"تسجيل نتيجة التواصل",followup_next:"تحديد المتابعة القادمة"};
 return <><div className="crm-profile-hero"><span className="crm-avatar">{contact.name?.slice(0,1)}</span><div><h2>{contact.name}</h2><p dir="ltr">{contact.phone}</p><small>{sources[contact.source||""]} · {contact.active?"نشط":"مؤرشف"}</small></div><div className="crm-phone-actions"><a href={`tel:${contact.phone}`} aria-label="اتصال"><Phone size={17}/></a><a href={`https://wa.me/${contact.phone?.replace(/\D/g,"")}`} target="_blank" rel="noreferrer" aria-label="فتح واتساب"><MessageCircle size={17}/></a></div></div>
 <div className="crm-profile-totals">{[["طلبات",stats.inquiries],["مواعيد",stats.appointments],["حضور",stats.attended],["متابعات مفتوحة",stats.openTasks]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
 <div className="crm-profile-actions"><button className="button outline" onClick={()=>onEdit("contacts",contact)}><Pencil size={15}/> تعديل</button><button className="button primary" onClick={()=>onAdd("inquiries",preset)}><Plus size={15}/> طلب حجز</button><button className="button outline" onClick={()=>onAdd("tasks",preset)}><ListChecks size={15}/> متابعة</button></div>
 {nextTask&&<button className={`crm-next-action ${Date.parse(nextTask.due_at!)<now?"is-overdue":""}`} onClick={()=>onEdit("tasks",{...nextTask,contact_name:contact.name})}><span>الخطوة القادمة {Date.parse(nextTask.due_at!)<now?"· متأخرة":""}</span><strong>{nextTask.title}</strong><small>{displayDate(nextTask.due_at)} · {owner(nextTask.owner)}</small></button>}
 {contact.note&&<p className="crm-profile-note">{contact.note}</p>}
 <div className="crm-tabs"><button className={tab==="records"?"active":""} onClick={()=>setTab("records")}>الطلبات والمتابعات</button><button className={tab==="timeline"?"active":""} onClick={()=>setTab("timeline")}>سجل رحلة العميل</button></div>
 {tab==="timeline"?<><p className="crm-muted">آخر 100 عملية محفوظة، بتاريخها الفعلي.</p><ol className="crm-customer-timeline">{detail.timeline.map(x=><li key={x.id}><time>{displayDate(x.created_at)}</time><strong>{actions[x.action]||x.action} {x.action==="booking_sync"?"":labels[x.entity]}</strong><small>{owner(x.actor)} · {x.record_id.slice(0,8)}</small></li>)}</ol>{!detail.timeline.length&&<p className="crm-muted">لم تُسجل عمليات بعد.</p>}</>:<>
 <section><h3>طلبات الحجز <small>{stats.inquiries}</small></h3>{detail.inquiries.map(r=><div key={r.id} className="crm-profile-request"><button className="crm-profile-row" onClick={()=>onEdit("inquiries",{...r,contact_name:contact.name})}><span><strong>{r.exam}</strong><small>{displayDate(r.created_at)} · {sources[r.source||""]}{r.physician_name&&" · "+r.physician_name}</small></span><span className={`crm-badge crm-${r.stage}`}>{stages[r.stage||""]}</span></button>{!["completed","cancelled"].includes(r.stage||"")&&<button className="crm-edit" onClick={()=>onAdd("tasks",{...preset,inquiry_id:r.id,inquiry_exam:r.exam,owner:r.owner,title:`متابعة طلب ${r.exam}`})}><Plus size={14}/> متابعة هذا الطلب</button>}</div>)}{!detail.inquiries.length&&<p className="crm-muted">لم تُسجل طلبات بعد.</p>}</section>
 <section><h3>المواعيد <small>{stats.appointments}</small></h3>{detail.appointments.map(r=><button className="crm-profile-row" key={r.id} onClick={()=>onEdit("appointments",{...r,contact_name:contact.name})}><span><strong>{r.exam}</strong><small>{displayDate(r.starts_at)}</small></span><span className={`crm-badge crm-${r.status}`}>{appointmentStatuses[r.status||""]}</span></button>)}{!detail.appointments.length&&<p className="crm-muted">لم تُسجل مواعيد بعد.</p>}</section>
 <section><h3>المتابعات</h3>{detail.tasks.map(r=><button className="crm-profile-row" key={r.id} onClick={()=>onEdit("tasks",{...r,contact_name:contact.name})}><span><strong>{r.title}</strong><small>{displayDate(r.due_at)} · {owner(r.owner)}{r.inquiry_exam&&` · ${r.inquiry_exam}`}</small>{r.followup_outcome&&<small>{followupOutcomes[r.followup_outcome]}{r.outcome_note&&" · "+r.outcome_note}</small>}</span><span className={`crm-badge crm-${r.status}`}>{r.status==="done"?"مكتملة":"مفتوحة"}</span></button>)}{!detail.tasks.length&&<p className="crm-muted">لم تُسجل متابعات بعد.</p>}</section><p className="crm-muted">يعرض أحدث 50 سجلًا من كل نوع. الأعداد تشمل كل سجلات العميل.</p>
 </>}
 </>;
}
