"use client";
import { useEffect, useState } from "react";
import { Check, LoaderCircle, Search, UserRound } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { crmRequest } from "@/lib/crm/client";
import { PhysicianPicker } from "@/components/referrals/physician-picker";
import { appointmentStatuses, exams, localInput, resources, roles, sources, stages, type CRMRecord, type Entity, type TeamMember } from "@/lib/crm/types";

const examResource=(exam?:string)=>exam?.includes("رنين")?"MRI":exam?.includes("سونار")||exam?.includes("دوبلر")?"US":"OTHER";
const labels:Record<Entity,string>={contacts:"جهة اتصال",inquiries:"طلب حجز",appointments:"موعد",tasks:"مهمة متابعة"};
function Select({label,value,onChange,options,empty,disabled=false,mustChoose=false}:{label:string;value?:string;onChange:(value:string)=>void;options:Record<string,string>;empty?:string;disabled?:boolean;mustChoose?:boolean}) {
 return <label className="crm-field"><span>{label}</span><select value={value||""} onChange={e=>onChange(e.target.value)} required={mustChoose||!empty} disabled={disabled}>{empty&&<option value="">{empty}</option>}{Object.entries(options).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>;
}
function ContactPicker({value,label,onChange,optional=false,disabled=false}:{value?:string;label?:string;onChange:(r:CRMRecord|null)=>void;optional?:boolean;disabled?:boolean}) {
 const [search,setSearch]=useState(""); const [rows,setRows]=useState<CRMRecord[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [open,setOpen]=useState(!value);
 useEffect(()=>{
  if(!open)return;
  const controller=new AbortController(); const timer=setTimeout(()=>{setLoading(true);setError("");crmRequest<{rows:CRMRecord[]}>("list",{entity:"contacts",search,status:"active"},controller.signal).then(r=>setRows(r.rows)).catch(e=>{if(e.name!=="AbortError")setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},250);
  return()=>{controller.abort();clearTimeout(timer);};
 },[search,open]);
 return <div className="crm-field crm-full"><span>جهة الاتصال {optional&&<small>· اختياري</small>}</span>{value&&!open?<div className="crm-selected-contact"><UserRound size={18}/><strong>{label||"جهة الاتصال المحددة"}</strong>{!disabled&&<button type="button" onClick={()=>setOpen(true)}>تغيير</button>}{optional&&!disabled&&<button type="button" onClick={()=>onChange(null)}>إزالة</button>}</div>:<><div className="crm-search"><Search size={17}/><input aria-label="بحث عن جهة اتصال" value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث بالاسم أو الهاتف…" maxLength={100}/></div><div className="crm-contact-options">{loading?<p>جارٍ البحث…</p>:error?<p role="alert">{error}</p>:rows.length?rows.map(r=><button type="button" key={r.id} onClick={()=>{onChange(r);setOpen(false);}}><span><strong>{r.name}</strong><small dir="ltr">{r.phone}</small></span><Check size={16}/></button>):<p>لا توجد نتائج. أضف جهة اتصال من صفحة جهات الاتصال أولًا.</p>}</div></>}</div>;
}
function InquiryPicker({contactId,value,onChange}:{contactId?:string;value?:string;onChange:(r:CRMRecord|null)=>void}) {
 const [rows,setRows]=useState<CRMRecord[]>([]);const [error,setError]=useState("");const [loadedContact,setLoadedContact]=useState("");
 useEffect(()=>{if(!contactId)return;const c=new AbortController();crmRequest<{rows:CRMRecord[]}>("list",{entity:"inquiries",contact_id:contactId},c.signal).then(r=>{if(c.signal.aborted)return;setRows(r.rows);setError("");setLoadedContact(contactId);}).catch(e=>{if(!c.signal.aborted){setRows([]);setError(e.message);setLoadedContact(contactId);}});return()=>c.abort();},[contactId]);
 return contactId?<label className="crm-field crm-full"><span>ربط المتابعة بطلب حجز · اختياري</span><select value={value||""} disabled={loadedContact!==contactId} onChange={e=>onChange(rows.find(r=>r.id===e.target.value)||null)}><option value="">{loadedContact!==contactId?"جارٍ تحميل الطلبات…":"متابعة عامة لجهة الاتصال"}</option>{loadedContact===contactId&&rows.map(r=><option value={r.id} key={r.id}>{r.exam} · {stages[r.stage||""]} · {r.id.slice(0,8)}</option>)}</select>{loadedContact===contactId&&error&&<small role="alert">{error}</small>}<small>يعرض أحدث 50 طلبًا. للطلبات الأقدم، افتح الطلب من سجله وأنشئ المتابعة منه.</small></label>:null;
}
export function RecordEditor({entity,record,staff,onClose,onSaved}:{entity:Entity;record:CRMRecord;staff:TeamMember[];onClose:()=>void;onSaved:()=>void}) {
 const [form,setForm]=useState<CRMRecord>(()=>({source:"phone",stage:"new",status:entity==="tasks"?"open":"scheduled",priority:"normal",resource:examResource(record.exam),exam:"",active:true,note:"",...record}));
 const [starts,setStarts]=useState(()=>localInput(record.starts_at)); const [due,setDue]=useState(()=>localInput(record.due_at));
 const [duration,setDuration]=useState(()=>record.starts_at&&record.ends_at?String(Math.round((Date.parse(record.ends_at)-Date.parse(record.starts_at))/60000)):"30");
 const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const field=(k:keyof CRMRecord,v:string|boolean|undefined)=>setForm(f=>({...f,[k]:v}));
 async function submit(e:React.FormEvent<HTMLFormElement>) {
  e.preventDefault();setError("");
  if(entity!=="contacts"&&entity!=="tasks"&&!form.contact_id){setError("اختر جهة اتصال قبل الحفظ.");return;}
  setBusy(true);
  try {
   const payload:Record<string,unknown>={...form,entity};
   if(entity==="appointments") { const start=new Date(`${starts}:00+03:00`);payload.starts_at=start.toISOString();payload.ends_at=new Date(start.getTime()+Number(duration)*60000).toISOString(); }
   if(entity==="tasks")payload.due_at=new Date(`${due}:00+03:00`).toISOString();
   await crmRequest("save",payload);onSaved();
  }catch(e){setError(e instanceof Error?e.message:"تعذّر الحفظ.");}finally{setBusy(false);}
 }
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent dir="rtl" className="crm-dialog"><DialogHeader><span className="eyebrow">SAMA SCAN · CRM</span><DialogTitle>{record.version?"تعديل":"إضافة"} {labels[entity]}</DialogTitle><DialogDescription>{entity==="appointments"?"كل المواعيد بتوقيت الرياض. يتحقق النظام من توافر الجهاز عند الحفظ.":"سجّل بيانات التواصل والمتابعة اللازمة لفريق المركز."}</DialogDescription></DialogHeader><form className="crm-form" onSubmit={submit}>
 {entity==="contacts"?<><label className="crm-field"><span>الاسم *</span><input required minLength={2} maxLength={100} value={form.name||""} onChange={e=>field("name",e.target.value)} autoComplete="off"/></label><label className="crm-field"><span>رقم الهاتف *</span><input required type="tel" dir="ltr" inputMode="tel" maxLength={20} placeholder="05xxxxxxxx" value={form.phone||""} onChange={e=>field("phone",e.target.value)} autoComplete="off"/></label></>:<ContactPicker value={form.contact_id} label={form.contact_name} disabled={entity==="appointments"&&record.version>0||Boolean(record.inquiry_id)} optional={entity==="tasks"} onChange={r=>setForm(f=>({...f,contact_id:r?.id,contact_name:r?.name,...(entity==="tasks"?{inquiry_id:undefined,inquiry_exam:undefined}:{})}))}/>}
 {(entity==="contacts"||entity==="inquiries")&&<Select label="مصدر التواصل" value={form.source} options={sources} onChange={v=>setForm(f=>({...f,source:v,...(entity==="inquiries"&&v!=="referral"?{referring_physician_id:undefined,physician_name:undefined}:{})}))}/>}
 {entity==="inquiries"&&form.source==="referral"&&<PhysicianPicker value={form.referring_physician_id} label={form.physician_name} optional onChange={d=>setForm(f=>({...f,referring_physician_id:d?.id,physician_name:d?.name}))}/>}
 {(entity==="inquiries"||entity==="appointments")&&<label className="crm-field"><span>الفحص المطلوب *</span><input list="crm-exams" value={form.exam||""} onChange={e=>setForm(f=>({...f,exam:e.target.value,...(entity==="appointments"?{resource:examResource(e.target.value)}:{})}))} required minLength={2} maxLength={100}/><datalist id="crm-exams">{exams.map(x=><option key={x} value={x}/>)}</datalist></label>}
 {entity==="inquiries"&&<Select label="مرحلة الطلب" value={form.stage} options={Object.fromEntries(Object.entries(stages).filter(([k])=>["new","contacting","waiting","cancelled",record.stage].includes(k)))} onChange={v=>field("stage",v)}/>}
 {entity==="appointments"&&<><Select label="الجهاز / غرفة الفحص" value={form.resource} options={resources} onChange={v=>field("resource",v)}/><label className="crm-field"><span>بداية الموعد · الرياض *</span><input type="datetime-local" required value={starts} onChange={e=>setStarts(e.target.value)}/></label><label className="crm-field"><span>مدة الموعد بالدقائق *</span><input type="number" min={5} max={480} step={5} value={duration} onChange={e=>setDuration(e.target.value)} required/></label><Select label="حالة الموعد" value={form.status} options={appointmentStatuses} onChange={v=>field("status",v)}/></>}
 {entity==="tasks"&&<>{record.inquiry_id?<div className="crm-field crm-full"><span>الطلب المرتبط</span><strong>{form.inquiry_exam||record.inquiry_id.slice(0,8)}</strong></div>:<InquiryPicker contactId={form.contact_id} value={form.inquiry_id} onChange={r=>setForm(f=>({...f,inquiry_id:r?.id,inquiry_exam:r?.exam}))}/>}<label className="crm-field crm-full"><span>المهمة *</span><input required minLength={2} maxLength={160} value={form.title||""} onChange={e=>field("title",e.target.value)} placeholder="مثل: تأكيد موعد الغد"/></label><label className="crm-field"><span>موعد المتابعة · الرياض *</span><input type="datetime-local" required value={due} onChange={e=>setDue(e.target.value)}/></label><Select label="الأولوية" value={form.priority} options={{normal:"عادية",high:"عالية"}} onChange={v=>field("priority",v)}/><Select label="الحالة" value={form.status} options={{open:"مفتوحة",done:"مكتملة"}} onChange={v=>field("status",v)}/></>}
 {(entity==="tasks"||entity==="inquiries")&&<Select label="المسؤول عن المتابعة" mustChoose={entity==="tasks"&&Boolean(form.inquiry_id)} value={form.owner} empty="غير معيّن" options={Object.fromEntries(staff.map(x=>[x.username,x.display_name]))} onChange={v=>field("owner",v)}/>}
 {entity==="contacts"&&record.version>0&&<Select label="حالة جهة الاتصال" value={form.active?"active":"inactive"} options={{active:"نشطة",inactive:"مؤرشفة"}} onChange={v=>field("active",v==="active")}/>}
 <label className="crm-field crm-full"><span>ملاحظات المتابعة</span><textarea value={form.note||""} onChange={e=>field("note",e.target.value)} maxLength={1000} rows={3} placeholder="ملاحظات إدارية لتسهيل التواصل والحجز"/></label>
 {error&&<div className="crm-error crm-full" role="alert">{error}</div>}
 <div className="crm-dialog-actions crm-full"><button className="button primary" disabled={busy} type="submit">{busy?<LoaderCircle className="crm-spin" size={17}/>:<Check size={17}/>} {busy?"جارٍ الحفظ…":"حفظ البيانات"}</button><button className="button outline" type="button" disabled={busy} onClick={onClose}>إلغاء</button></div>
 </form></DialogContent></Dialog>;
}
export function TeamEditor({record,onClose,onSaved}:{record:TeamMember|null;onClose:()=>void;onSaved:()=>void}) {
 const [username,setUsername]=useState(record?.username||"");const [name,setName]=useState(record?.display_name||"");const [role,setRole]=useState(record?.role||"reception");const [active,setActive]=useState(record?.active??true);const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{await crmRequest("save_user",{username,display_name:name,role,active,password:password||undefined,creating:!record,updated_at:record?.updated_at});onSaved();}catch(e){setError(e instanceof Error?e.message:"تعذّر الحفظ");}finally{setBusy(false);}}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent dir="rtl" className="crm-dialog"><DialogHeader><DialogTitle>{record?"إدارة حساب الموظف":"إضافة حساب للفريق"}</DialogTitle><DialogDescription>الاستقبال يدير العملاء والمواعيد. التسويق يدير علاقات الأطباء وزياراته ويرى تقارير الإحالات الإجمالية والأداء والمحتوى. الإدارة تملك كل الصلاحيات.</DialogDescription></DialogHeader><form className="crm-form" onSubmit={submit}><label className="crm-field"><span>اسم الموظف *</span><input required minLength={2} maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label className="crm-field"><span>اسم الدخول *</span><input dir="ltr" required disabled={Boolean(record)} pattern="[a-zA-Z0-9_.\-]{3,40}" maxLength={40} value={username} onChange={e=>setUsername(e.target.value)} autoComplete="off"/></label><Select label="الصلاحية" options={roles} value={role} onChange={v=>setRole(v as typeof role)}/><Select label="حالة الحساب" options={{active:"نشط",disabled:"موقوف"}} value={active?"active":"disabled"} onChange={v=>setActive(v==="active")}/><label className="crm-field crm-full"><span>{record?"كلمة مرور جديدة · اتركها فارغة للاحتفاظ بالحالية":"كلمة المرور *"}</span><input type="password" required={!record} minLength={10} maxLength={72} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password" dir="ltr"/></label>{record&&<p className="crm-muted crm-full">عند حفظ التغيير، تُنهى جلسات هذا الحساب ويحتاج لتسجيل الدخول مجددًا.</p>}{error&&<div className="crm-error crm-full" role="alert">{error}</div>}<div className="crm-dialog-actions crm-full"><button className="button primary" disabled={busy}>{busy?"جارٍ الحفظ…":"حفظ الحساب"}</button><button type="button" className="button outline" disabled={busy} onClick={onClose}>إلغاء</button></div></form></DialogContent></Dialog>;
}
