"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { Activity, BarChart3, Bell, CalendarDays, ChevronLeft, CircleHelp, ExternalLink, Eye, Globe2, ImagePlus, Info, MapPin, MessageCircle, MousePointer2, Phone, Send, ShieldCheck, Sparkles, Target, TrendingUp, Megaphone, UsersRound, X } from "lucide-react";
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { snapshot, percentChange } from "@/lib/dashboard/snapshot";
import { GoogleComparisonChart, SearchChart, CompetitorMixChart } from "@/components/dashboard-charts";

const nav = [
  { id: "overview", title: "نظرة عامة", icon: BarChart3 },
  { id: "google", title: "الملف التجاري", icon: MapPin },
  { id: "website", title: "أداء الموقع", icon: Globe2 },
  { id: "ads", title: "قياس الإعلانات", icon: Megaphone },
  { id: "competitors", title: "مشهد المنافسة", icon: UsersRound },
  { id: "improvements", title: "فرص التحسين", icon: Sparkles },
  { id: "publisher", title: "النشر الجماعي", icon: Send },
  { id: "channels", title: "قنوات المركز", icon: MessageCircle },
] as const;
type View = typeof nav[number]["id"];
const navGroups = [
  { label: "لوحة المركز", ids: ["overview"] },
  { label: "الأداء والقياس", ids: ["google", "website", "ads"] },
  { label: "النمو والمحتوى", ids: ["competitors", "improvements", "publisher", "channels"] },
] as const;
const tasks = [
  { title: "تسهيل الاتصال والوصول", text: "اختبر زر الاتصال والاتجاهات من الجوال، وسجّل المكالمات المجابة والفائتة وتابع الفائتة أثناء الدوام.", owner: "الاستقبال + مدير الملف" },
  { title: "تحسين صفحات الفحوصات", text: "راجع أول شاشة في صفحات الرنين والسونار والدوبلر و3D/4D: اسم الفحص، التحضير المعتمد، وزر اتصال واضح.", owner: "المطور + المركز" },
  { title: "زيادة نقرات البحث", text: "راجع عنوان ووصف الصفحات ذات الظهور دون نقرات، وافحص الروابط ذات معاملات UTM والربط الداخلي.", owner: "المطور + مسؤول المحتوى" },
  { title: "محتوى وصور أصلية", text: "جهّز منشورين أسبوعيًا بعد مراجعة المعلومات الطبية، وأضف صورًا حديثة للمدخل والاستقبال والأجهزة بموافقة المركز.", owner: "المركز + مسؤول المحتوى" },
];
const format = (n: number, digits = 0) => new Intl.NumberFormat("en-US", { maximumFractionDigits: digits }).format(n);
const date = (iso: string) => new Intl.DateTimeFormat("ar-SA", { calendar: "gregory", day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${iso}T12:00:00Z`));
const periodLabel = (from: string, to: string) => `${date(from)} – ${date(to)}`;
const gbp = snapshot.google;
const search = snapshot.search;
const stats = [
  { title: "ضغطات الاتصال", key: "calls", icon: Phone, accent: true },
  { title: "طلبات الاتجاهات", key: "directions", icon: MapPin },
  { title: "مشاهدات الملف", key: "views", icon: Eye },
  { title: "نقرات الموقع من الملف", key: "website", icon: MousePointer2 },
] as const;
const competitors = [
  { name: "الاستشاريون للأشعة CRC", kind: "مركز أشعة", focus: "العليا · الرياض", services: "الرنين، السونار، الأشعة المقطعية", strength: "طلب موعد بخطوات واضحة", href: "https://crc-scan.com/AR/main/home_4.aspx" },
  { name: "رادكير", kind: "مركز أشعة", focus: "عدة فروع بالرياض", services: "الرنين، السونار، الأشعة المقطعية", strength: "عرض واسع للخدمات والفروع", href: "https://radcarehealth.com/" },
  { name: "المتحالف للأشعة", kind: "مركز أشعة", focus: "طريق الملك عبدالعزيز · الرياض", services: "الرنين، السونار، الأشعة المقطعية", strength: "خدمات متنقلة وحجز موعد", href: "https://allieddiagnostics.net/ar/" },
  { name: "قسم الأشعة بمستشفى دله", kind: "قسم مستشفى", focus: "الرياض", services: "الرنين، السونار، الأشعة المقطعية", strength: "نتائج الفحوصات عبر التطبيق", href: "https://www.dallah-hospital.com/Arabic/Radiology" },
  { name: "أشعة مستشفى فقيه الرياض", kind: "قسم مستشفى", focus: "الرياض", services: "الرنين، السونار، الأشعة المقطعية", strength: "عرض تفاصيل الأجهزة والفحوصات", href: "https://dsfhriyadh.fakeeh.care/facilities/radiology" },
] as const;
const overviewCards = [
  { view: "google", icon: MapPin, label: "الملف التجاري", value: "118 ضغطة اتصال", detail: "نمو 555.6% مقارنة بالفترة السابقة", tone: "teal" },
  { view: "website", icon: Globe2, label: "أداء الموقع", value: "741 ظهورًا", detail: "16 نقرة من نتائج البحث", tone: "blue" },
  { view: "ads", icon: Megaphone, label: "أهداف الإعلانات", value: "4,000 ر.س", detail: "ميزانية شهرية مقترحة · 24 تواصلًا مستهدفًا", tone: "gold" },
  { view: "competitors", icon: UsersRound, label: "مشهد المنافسة", value: "5 جهات", detail: "3 مراكز أشعة وقسمان بمستشفيات", tone: "violet" },
  { view: "improvements", icon: Sparkles, label: "فرص التحسين", value: "4 أولويات", detail: "التواصل، صفحات الفحوصات، البحث والمحتوى", tone: "green" },
  { view: "publisher", icon: Send, label: "النشر الجماعي", value: "3 قنوات", detail: "جهّز منشورًا وعاين توزيعه على الصفحات", tone: "coral" },
  { view: "channels", icon: MessageCircle, label: "قنوات المركز", value: "13 منشورًا", detail: "سجل المنشورات الظاهرة في الملف وقت التقرير", tone: "slate" },
] as const;
function Metric({title, value, previous, icon: Icon, accent = false}: {title:string;value:number;previous:number;icon:typeof Phone;accent?:boolean}) {
  const delta = percentChange(value, previous);
  return <article className={`metric ${accent ? "metric-accent" : ""}`}><div className="metric-top"><span>{title}</span><span className="metric-icon"><Icon size={19}/></span></div><strong className="metric-value" dir="ltr">{format(value)}</strong><div className="metric-change"><span className="delta positive" dir="ltr">+{format(delta ?? 0, 1)}% <TrendingUp size={13}/></span><span>{format(previous)} سابقًا</span></div></article>;
}
function PeriodNote() { return <div className="filterbar"><div className="period"><CalendarDays size={17}/><span>فترة الملف: {periodLabel(gbp.current.from, gbp.current.to)}</span></div><div className="filter-status"><span>تقرير موثق بتاريخ {date(snapshot.issued)} · بيانات محفوظة</span></div></div>; }
export default function Dashboard() {
  const [view, setView] = useState<View>("overview");
  const [notificationOpen, setNotificationOpen] = useState(true);
  const [greetingAvailable, setGreetingAvailable] = useState(true);
  const [clock, setClock] = useState("");
  const [targets, setTargets] = useState<string[]>(["ملف Google", "فيسبوك", "إنستغرام"]);
  const [distribution, setDistribution] = useState(false);
  const [help, setHelp] = useState(false);
  const [body, setBody] = useState("");
  const [image, setImage] = useState<string | null>(null);
  const [imageName, setImageName] = useState("");
  const [copied, setCopied] = useState(false);
  useEffect(() => {
    const time = () => setClock(new Intl.DateTimeFormat("ar-SA", { timeZone: "Asia/Riyadh", hour: "2-digit", minute: "2-digit", hour12: true }).format(new Date()));
    time(); const tick = window.setInterval(time, 60000);
    const dismiss = window.setTimeout(() => { setNotificationOpen(false); setGreetingAvailable(false); }, 45000);
    return () => { window.clearInterval(tick); window.clearTimeout(dismiss); };
  }, []);
  const active = nav.find(n => n.id === view)!;
  function selectImage(file?: File) {
    if (!file) return;
    if (!["image/jpeg", "image/png"].includes(file.type) || file.size > 4 * 1024 * 1024) { alert("اختر صورة JPG أو PNG حتى 4 ميجابايت."); return; }
    const reader = new FileReader();
    reader.onload = () => { if (typeof reader.result === "string") { setImage(reader.result); setImageName(file.name); } };
    reader.readAsDataURL(file);
  }
  async function copyPost() { try { await navigator.clipboard.writeText(body); setCopied(true); setTimeout(() => setCopied(false), 2500); } catch { alert("تعذّر النسخ، حدّد النص وانسخه يدويًا."); } }
  return <SidebarProvider style={{ "--sidebar-width": "16rem" } as React.CSSProperties}>
    <Sidebar side="right" className="sama-sidebar"><SidebarHeader className="brand"><Image src="/sama-scan-logo.png" width={160} height={160} alt="شعار سما سكان"/><div><strong>سما سكان</strong><span>مركز الأشعة التشخيصية</span></div></SidebarHeader><SidebarContent>
      {navGroups.map(group => <div className="sidebar-group" key={group.label}><div className="sidebar-caption">{group.label}</div><SidebarMenu className="nav-menu">{nav.filter(n => (group.ids as readonly string[]).includes(n.id)).map(n => <SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view === n.id} onClick={() => setView(n.id)} className={`nav-item ${n.id === "overview" ? "nav-overview" : ""}`}><span className="nav-icon"><n.icon/></span><span>{n.title}</span>{n.id === "overview" && <span className="nav-home-mark" aria-hidden="true"/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></div>)}
      <div className="sidebar-health"><span className="health-icon"><Activity size={20}/></span><strong>آخر تقرير متاح</strong><p>{date(snapshot.issued)}<br/>أرقام تاريخية موثقة، وليست قراءة مباشرة.</p><button onClick={() => setView("improvements")}>خطة التحسين <Target size={14}/></button></div>
    </SidebarContent><SidebarFooter className="sidebar-bottom"><div className="user-avatar">س</div><div><strong>إدارة سما سكان</strong><span>لوحة خاصة بالمركز</span></div><ShieldCheck size={18}/></SidebarFooter></Sidebar>
    <SidebarInset className="app-main"><header className="topbar"><div className="breadcrumb"><SidebarTrigger aria-label="فتح قائمة التنقل" className="mobile-menu"/><button className="breadcrumb-home" onClick={() => setView("overview")}>مساحة سما سكان</button><ChevronLeft size={15}/><strong>{active.title}</strong></div><div className="topbar-tools"><a href="/" target="_blank" rel="noreferrer"><Globe2 size={16}/><span>زيارة الموقع</span><ExternalLink size={13}/></a><span className="private-chip"><ShieldCheck size={14}/> لوحة خاصة</span><span className="riyadh-clock" suppressHydrationWarning>{clock ? `الرياض · ${clock}` : "الرياض"}</span>
      <div className="notification-wrap"><button className={`icon-button notification-trigger ${greetingAvailable ? "has-notification" : ""}`} type="button" onClick={() => setNotificationOpen(v => !v)} aria-label="الإشعارات" aria-expanded={notificationOpen} aria-controls="sama-notifications"><Bell size={21}/>{greetingAvailable && <i className="notification-dot" aria-hidden="true"/>}</button>{notificationOpen && <div className="notification-popover" id="sama-notifications" role="status"><div className="notification-head"><span><Bell size={16}/> الإشعارات</span><button type="button" onClick={() => setNotificationOpen(false)} aria-label="إغلاق الإشعارات"><X size={17}/></button></div>{greetingAvailable ? <div className="notification-greeting"><span className="notification-avatar" aria-hidden="true">🧑🏻‍⚕️</span><div><strong>نورت يا دكتور 🧑🏻‍⚕️</strong><p>أهلًا بك في مساحة سما سكان. صورة الأداء وفرص النمو جاهزة لك.</p><small>مرحبًا بعودتك</small></div></div> : <p className="notification-empty">لا توجد إشعارات جديدة الآن</p>}</div>}</div>
      <form action="/api/dashboard/logout" method="post"><button className="text-link" type="submit">خروج</button></form><button className="icon-button" onClick={() => setHelp(true)} aria-label="تعريف المقاييس"><CircleHelp size={20}/></button></div></header>
      <main className="workspace"><div className="page-heading"><div><span className="eyebrow">SAMA SCAN · DIGITAL GROWTH</span><h1>{view === "overview" ? "صورة أوضح لأداء المركز" : active.title}</h1><p>{view === "publisher" ? "تجربة توزيع منشور واحد على قنوات المركز." : "أرقام الأداء، الاتجاهات، وخطوات النمو في مساحة واحدة."}</p></div>{view !== "publisher" && <button className="button primary" onClick={() => setView("publisher")}><Send size={17}/> النشر الجماعي</button>}</div>
      {view === "overview" && <div className="snapshot-hero"><div><span className="hero-kicker">لوحة أداء سما سكان</span><h2>نمو الظهور والتواصل، بصورة أوضح.</h2><p>الملف التجاري · بحث الموقع · خطة التحسين</p></div><div className="hero-date"><CalendarDays size={18}/><span>آخر بيانات<br/><strong>{date(snapshot.issued)}</strong></span></div></div>}
      {(view === "overview" || view === "google") && <><PeriodNote/><div className="metrics-grid">{stats.map(s => <Metric key={s.key} title={s.title} value={gbp.current[s.key]} previous={gbp.previous[s.key]} icon={s.icon} accent={"accent" in s && s.accent}/>)}</div>
        {view === "overview" ? <><div className="chart-grid"><section className="panel"><div className="panel-title"><div><h2>التفاعل مع الملف التجاري</h2><p>السابق مقابل الفترة الحالية · 32 يومًا لكل فترة</p></div><span className="source-tag">تقرير 29 سبتمبر</span></div><div className="chart-legend"><span><i className="navy"/>السابق</span><span><i className="cyan"/>الحالي</span></div><GoogleComparisonChart/></section><aside className="insight-panel"><div className="insight-top"><span className="insight-icon"><Sparkles size={21}/></span><span>الخطوة التالية</span></div><h2>حوّل الاهتمام إلى تواصل فعلي</h2><p>سجل الملف {format(gbp.current.calls)} ضغطة اتصال و{format(gbp.current.directions)} طلب اتجاهات. اختبر سهولة الوصول، وسجل الردود والحجوزات قبل زيادة النشر.</p><div className="insight-divider"/><div className="insight-stat"><span>حصة الجوال من المشاهدات</span><strong>{format(gbp.mobileShare, 1)}%</strong></div><button className="button light" onClick={() => setView("improvements")}>عرض فرص التحسين <Target size={17}/></button></aside></div><section className="overview-hub" aria-labelledby="overview-hub-title"><div className="overview-hub-head"><div><span className="eyebrow">استكشف مساحة المركز</span><h2 id="overview-hub-title">كل مسار يبدأ من هنا</h2><p>مقتطف سريع من كل قسم، ثم افتح التفاصيل بضغطة واحدة.</p></div><span className="overview-hub-count">7 مسارات</span></div><div className="overview-grid">{overviewCards.map(card => <button className={`overview-card tone-${card.tone}`} type="button" key={card.view} onClick={() => setView(card.view)}><span className="overview-card-top"><span className="overview-card-icon"><card.icon size={21}/></span><span className="overview-card-arrow"><ChevronLeft size={18}/></span></span><span className="overview-card-label">{card.label}</span><strong>{card.value}</strong><span className="overview-card-detail">{card.detail}</span><span className="overview-card-cta">استعرض التفاصيل <ChevronLeft size={15}/></span></button>)}</div></section></> : <section className="panel data-table"><div className="panel-title"><div><h2>المقارنة التفصيلية</h2><p>{periodLabel(gbp.previous.from, gbp.previous.to)} مقابل {periodLabel(gbp.current.from, gbp.current.to)}</p></div></div><Table><TableHeader><TableRow><TableHead>المقياس</TableHead><TableHead>السابقة</TableHead><TableHead>الحالية</TableHead><TableHead>التغير</TableHead></TableRow></TableHeader><TableBody>{stats.map(s => <TableRow key={s.key}><TableCell>{s.title}</TableCell><TableCell>{format(gbp.previous[s.key])}</TableCell><TableCell>{format(gbp.current[s.key])}</TableCell><TableCell><span className="delta positive" dir="ltr">+{format(percentChange(gbp.current[s.key], gbp.previous[s.key]) ?? 0, 1)}%</span></TableCell></TableRow>)}</TableBody></Table><p className="small-note">ضغطات الاتصال ليست مكالمات مجابة، وطلبات الاتجاهات ليست زيارات مؤكدة. لم تدخل بيانات 27–29 سبتمبر غير المكتملة في هذه المقارنة.</p></section>}</>}
      {view === "website" && <><div className="filterbar"><div className="period"><CalendarDays size={17}/> Search Console حتى {date(search.through)}</div><span className="filter-status">آخر بيانات {date(search.through)}</span></div><div className="metrics-grid"><article className="metric metric-accent"><div className="metric-top">نقرات البحث <MousePointer2 size={19}/></div><strong className="metric-value">{format(search.clicks)}</strong><span className="small-note">حتى 29 سبتمبر</span></article><article className="metric"><div className="metric-top">مرات الظهور <Eye size={19}/></div><strong className="metric-value">{format(search.impressions)}</strong><span className="small-note">حتى 29 سبتمبر</span></article><article className="metric"><div className="metric-top">نسبة النقر <Target size={19}/></div><strong className="metric-value">{format(search.ctr,2)}%</strong><span className="small-note">النقرات ÷ الظهور</span></article><article className="metric"><div className="metric-top">متوسط الموضع <TrendingUp size={19}/></div><strong className="metric-value">{format(search.position,2)}</strong><span className="small-note">الأقل أفضل</span></article></div><section className="panel data-table"><div className="panel-title"><div><h2>مقارنة أسبوعين مكتملين</h2><p>{periodLabel(search.week.previous.from,search.week.previous.to)} مقابل {periodLabel(search.week.current.from,search.week.current.to)}</p></div></div><Table><TableHeader><TableRow><TableHead>المقياس</TableHead><TableHead>السابق</TableHead><TableHead>الأحدث</TableHead><TableHead>التغير</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>ظهور الموقع</TableCell><TableCell>261</TableCell><TableCell>342</TableCell><TableCell><span className="delta positive" dir="ltr">+31.0%</span></TableCell></TableRow><TableRow><TableCell>نقرات البحث</TableCell><TableCell>10</TableCell><TableCell>5</TableCell><TableCell><span className="delta negative" dir="ltr">−50.0%</span></TableCell></TableRow></TableBody></Table><SearchChart/></section><section className="panel"><h2>التواصل من الموقع</h2><p className="small-note">زيارات الموقع وضغطات الهاتف وواتساب والاتجاهات داخله غير متاحة في التقرير الأخير. الأرقام أعلاه من البحث، وليست جلسات موقع أو حجوزات.</p></section></>}
      {view === "ads" && <><div className="section-intro"><span className="eyebrow">CAMPAIGN PLANNER</span><h2>أهداف حملة بحث مقترحة</h2><p>ميزانية محسوبة لتحويل البحث عن الفحوصات إلى تواصل.</p></div><div className="metrics-grid"><article className="metric metric-accent"><div className="metric-top">ميزانية شهرية <Megaphone size={19}/></div><strong className="metric-value" dir="ltr">4,000 <small>ر.س</small></strong><span className="metric-change">هدف الإنفاق</span></article><article className="metric"><div className="metric-top">نقرات مستهدفة <MousePointer2 size={19}/></div><strong className="metric-value">320</strong><span className="metric-change">متوسط 12.5 ر.س للنقرة</span></article><article className="metric"><div className="metric-top">تواصل مستهدف <Phone size={19}/></div><strong className="metric-value">24</strong><span className="metric-change">اتصالات وطلبات تواصل</span></article><article className="metric"><div className="metric-top">معدل تواصل مستهدف <Target size={19}/></div><strong className="metric-value">7.5%</strong><span className="metric-change">24 ÷ 320 نقرة</span></article></div><section className="panel"><div className="panel-title"><div><h2>توزيع الميزانية المقترح</h2><p>توزيع شهري حسب نية البحث والوصول للمركز</p></div><span className="source-tag">4,000 ر.س</span></div><div className="budget-list">{[{label:"بحث خدمات الأشعة",value:2200,color:"#087f9c"},{label:"خرائط ونطاق المركز",value:1200,color:"#48b8c2"},{label:"إعادة استهداف",value:600,color:"#e6ad5d"}].map(item=><div className="budget-row" key={item.label}><div><strong>{item.label}</strong><span>{format(item.value)} ر.س · {format(item.value/40)}%</span></div><div className="budget-track"><i style={{width:`${item.value/40}%`,background:item.color}}/></div></div>)}</div></section></>}
      {view === "competitors" && <><div className="section-intro"><span className="eyebrow">RIYADH · RADIOLOGY LANDSCAPE</span><h2>خمس جهات تقدم فحوصات مماثلة بالرياض</h2><p>مقارنة الخدمات وطريقة عرضها في المواقع الرسمية.</p></div><div className="competitor-layout"><section className="panel competitor-summary"><div className="panel-title"><div><h2>توزيع جهات المقارنة</h2><p>حسب طبيعة الجهة</p></div><UsersRound size={20}/></div><CompetitorMixChart/><div className="mix-legend"><span><i className="cyan"/>3 مراكز أشعة</span><span><i className="navy"/>2 أقسام مستشفيات</span></div></section><section className="panel competitor-insight"><span className="eyebrow">فرصة سما سكان</span><h2>صفحة الخدمة المختصرة، مع تواصل فوري.</h2><p>ركّز في أول شاشة من كل فحص على اسمه، والتحضير المعتمد، وموقع المربع، وزر اتصال واضح. المنافسة على رحلة الحجز وسهولة الوصول، لا على عدد الخدمات وحده.</p><button className="button outline" onClick={()=>setView("improvements")}>استعرض خطة التحسين <Target size={16}/></button></section></div><div className="competitor-cards">{competitors.map((c,i)=><article className="competitor-card" key={c.name}><div className="competitor-top"><span className="competitor-rank">{String(i+1).padStart(2,"0")}</span><span className="badge neutral">{c.kind}</span></div><h3>{c.name}</h3><p className="competitor-place"><MapPin size={14}/>{c.focus}</p><div className="competitor-service">{c.services}</div><div className="competitor-bottom"><span>{c.strength}</span><a href={c.href} target="_blank" rel="noreferrer" aria-label={`زيارة موقع ${c.name}`}><ExternalLink size={16}/></a></div></article>)}</div></>}
      {view === "improvements" && <><div className="plan-heading"><div><Target size={26}/><div><h2>خطة التحسين</h2><p>أولويات عملية للموقع والملف التجاري.</p></div></div></div><div className="tasks-grid">{tasks.map((t,i) => <article className="task-card" key={t.title}><div className="task-number">{String(i+1).padStart(2,"0")}</div><div className="task-body"><span className="badge neutral">أولوية {String(i+1).padStart(2,"0")}</span><h3>{t.title}</h3><p>{t.text}</p><div className="task-footer">{t.owner}</div></div></article>)}</div></>}
      {view === "publisher" && <div className="editor-grid"><section className="panel editor-panel"><div className="panel-title"><div><h2>منشور واحد، صفحات متعددة</h2><p>تصور لواجهة توزيع المحتوى من مكان واحد</p></div><span className="badge neutral">معاينة</span></div>
        <div className="publish-channels">{["ملف Google", "فيسبوك", "إنستغرام"].map((name,i)=><label className={`publish-channel ${targets.includes(name)?"selected":""}`} key={name}><input type="checkbox" checked={targets.includes(name)} onChange={e=>setTargets(e.target.checked?[...targets,name]:targets.filter(t=>t!==name))}/><span className={`platform-dot platform-${i}`}>{["G","f","◎"][i]}</span><span>{name}<small>قناة ضمن تصور النشر الجماعي</small></span></label>)}</div>
        <label className="field-label" htmlFor="post-body">نص المنشور</label><textarea id="post-body" value={body} onChange={e=>setBody(e.target.value)} maxLength={1500} placeholder="اكتب نصًا يوضح الفحص ودعوة تواصل واحدة…"/><div className="text-meta"><span>راجع المعلومات الطبية مع المركز.</span><span dir="ltr">{body.length} / 1,500</span></div>
        <label className="upload-zone" htmlFor="post-image"><ImagePlus size={27}/><strong>{imageName || "اختيار صورة للمعاينة"}</strong><span>JPG أو PNG حتى 4 ميجابايت</span></label><input id="post-image" type="file" accept="image/jpeg,image/png" className="sr-only" onChange={e=>selectImage(e.target.files?.[0])}/>
        <div className="editor-actions"><button className="button primary" disabled={!body.trim()||targets.length===0} onClick={()=>setDistribution(true)}><Send size={16}/> معاينة النشر إلى {targets.length} قنوات</button><button className="button outline" disabled={!body.trim()} onClick={()=>void copyPost()}>{copied ? "تم النسخ" : "نسخ النص"}</button></div></section>
        <aside className="post-preview-wrap"><div className="preview-heading"><Eye size={17}/> معاينة المحتوى</div><article className="post-preview"><div className="post-author"><Image src="/sama-scan-icon.png" width={42} height={42} alt=""/><div><strong>مركز سما سكان للأشعة</strong><span>شكل المنشور قبل الإرسال</span></div></div><p className="post-copy">{body || "نص المنشور سيظهر هنا أثناء الكتابة."}</p>{image ? <Image unoptimized width={1200} height={900} className="post-image" src={image} alt="معاينة صورة المنشور"/> : <div className="preview-empty"><ImagePlus size={40}/><span>مساحة الصورة</span></div>}</article><div className="preview-guidance"><ShieldCheck size={20}/><p>يمكن معاينة شكل التوزيع هنا. النسخ اليدوي متاح للنص.</p></div></aside></div>}
      {view === "channels" && <><div className="connections-grid"><article className="connection-card"><div className="connection-card-top"><Globe2 size={26}/><span className="badge neutral">بيانات تقرير</span></div><h3>ملف Google التجاري</h3><p>المقاييس المعروضة من تقرير محفوظ بتاريخ 29 سبتمبر.</p><button className="text-button" onClick={()=>setView("google")}>عرض الأرقام ←</button></article><article className="connection-card"><div className="connection-card-top"><Eye size={26}/><span className="badge neutral">بيانات تقرير</span></div><h3>بحث الموقع</h3><p>الظهور والنقرات من Google Search Console كما وثقها التقرير.</p><button className="text-button" onClick={()=>setView("website")}>عرض الأرقام ←</button></article><article className="connection-card"><div className="connection-card-top"><Send size={26}/><span className="badge neutral">غير متصل للنشر</span></div><h3>الصفحات الاجتماعية</h3><p>النشر الجماعي غير مفعل. يمكن تجهيز المنشور هنا ثم نسخه للنشر اليدوي.</p><button className="text-button" onClick={()=>setView("publisher")}>تجهيز منشور ←</button></article></div><section className="panel"><h2>آخر المنشورات الموثقة</h2><p className="small-note">ظهر في الملف التجاري {snapshot.posts.count} منشورًا وقت استخراج التقرير؛ {snapshot.posts.callCta} بزر الاتصال و{snapshot.posts.learnMoreCta} بزر معرفة المزيد. العدد لا يعني أن كلها نُشرت خلال فترة المقارنة.</p></section></>}
      <footer className="workspace-footer"><span className="footer-brand"><Image src="/sama-scan-icon.png" width={42} height={42} alt=""/>سما سكان · وضوح في الصورة والقرار</span><div className="footer-meta"><button onClick={()=>setHelp(true)}>كيف نقرأ الأرقام؟ <Info size={14}/></button><span className="developer-signature">تصميم وتطوير <strong>المهندس إسلام الشيخ</strong></span></div></footer></main></SidebarInset>
      <Dialog open={distribution} onOpenChange={setDistribution}><DialogContent dir="rtl" className="review-dialog"><DialogHeader><DialogTitle>معاينة النشر الجماعي</DialogTitle><DialogDescription>تصور طريقة توزيع المنشور على القنوات المختارة.</DialogDescription></DialogHeader><div className="review-text">{body}</div><div className="review-targets">{targets.map(t=><div key={t}><span className="platform-dot">{t.slice(0,1)}</span><span>{t}<small>معاينة الصفحة</small></span><span className="badge neutral">معاينة</span></div>)}</div><button className="button primary" onClick={()=>setDistribution(false)}>إغلاق المعاينة</button></DialogContent></Dialog>
      <Dialog open={help} onOpenChange={setHelp}><DialogContent dir="rtl" className="method-dialog"><DialogHeader><DialogTitle>قراءة الأرقام بدقة</DialogTitle><DialogDescription>{snapshot.source}</DialogDescription></DialogHeader><dl><dt>ضغطات الاتصال</dt><dd>ضغط على زر الهاتف في الملف التجاري، ولا يثبت الرد أو الحجز.</dd><dt>طلبات الاتجاهات</dt><dd>طلب إرشادات الوصول؛ لا يثبت زيارة المركز.</dd><dt>نقرات المحادثة</dt><dd>9 ضغطات في ملف Google خلال سبتمبر حتى 29 منه؛ ليست قياسًا لواتساب الموقع.</dd><dt>نسب التحسن</dt><dd>مقارنة فترتين مكتملتين من 32 يومًا: 25 يوليو إلى 25 أغسطس و26 أغسطس إلى 26 سبتمبر. النسبة هي الفرق ÷ القيمة السابقة × 100.</dd><dt>بحث الموقع</dt><dd>بيانات Search Console حتى 29 سبتمبر، وفترة مختلفة عن مقارنة الملف التجاري. لا نجمع النقرات كمستخدمين فريدين.</dd></dl></DialogContent></Dialog>
  </SidebarProvider>;
}
