"use client";
import { useEffect, useState } from "react";
import { crmRequest } from "@/lib/crm/client";
import { displayDate, localInput, riyadhDay } from "@/lib/crm/types";
import { neighborhoods, type MedicalContent, type MapObservation, type GBPPeriod } from "@/lib/growth";
import { services } from "@/lib/site";
import { blogPosts } from "@/lib/blog";

type Inventory = { content: MedicalContent[]; maps: MapObservation[]; periods: GBPPeriod[] };
const blank = (kind: MedicalContent["kind"] = "service", id = services[0].slug): MedicalContent => ({ id, kind, data: {}, status: "draft", evidence: "", confirmed_by: "", confirmed_at: "", version: 0 });
const photos = { "": "لا تضف صورة جديدة", "/mri-room-sama-scan-riyadh.webp": "غرفة الرنين الحالية", "/mri-suite-sama-scan-riyadh.webp": "وحدة الرنين", "/ultrasound-room-sama-scan-riyadh.webp": "غرفة السونار", "/ultrasound-exam-room-riyadh.webp": "جهاز الموجات فوق الصوتية" };
export default function GrowthWorkspace() {
  const [tab, setTab] = useState("content");
  const [inventory, setInventory] = useState<Inventory | null>(null);
  const [revision, setRevision] = useState(0);
  const [loaded, setLoaded] = useState(-1);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);
  const [form, setForm] = useState<MedicalContent>(() => blank());
  const [attested, setAttested] = useState(false);
  const [article, setArticle] = useState(blogPosts[0].slug);
  const [rankResult, setRankResult] = useState("found");
  useEffect(() => {
    const c = new AbortController();
    crmRequest<Inventory>("growth_list", {}, c.signal).then(r => { if (!c.signal.aborted) { setInventory(r); setError(""); setLoaded(revision); } }).catch(e => { if (!c.signal.aborted) { setError(e.message); setLoaded(revision); } });
    return () => c.abort();
  }, [revision]);
  function choose(kind: MedicalContent["kind"], id: string) { setForm(inventory?.content.find(x => x.kind === kind && x.id === id) || blank(kind, id)); setAttested(false); setError(""); setNotice(""); }
  function field(key: string, value: string) { setForm(f => ({ ...f, data: { ...f.data, [key]: value } })); }
  async function save(action: string, payload: Record<string, unknown>) {
    setBusy(true); setError(""); setNotice("");
    try {
      const r = await crmRequest<{ data?: MedicalContent }>(action, payload);
      if (action === "growth_content_save" && r.data) { setForm(r.data); setAttested(false); }
      setNotice(action === "growth_content_save" ? payload.status === "approved" ? "حُفظ الاعتماد. يظهر المحتوى العام خلال 5 دقائق." : "حُفظت المسودة دون نشرها." : "حُفظ القياس بنجاح.");
      setRevision(n => n + 1);
    } catch (e) { setError(e instanceof Error ? e.message : "تعذّر الحفظ."); } finally { setBusy(false); }
  }
  const clinicians = inventory?.content.filter(x => x.kind === "clinician" && x.status === "approved") || [];
  return <div className="growth-workspace"><div className="crm-tabs" role="group" aria-label="إدارة التحسينات">{[["content", "اعتماد المحتوى الطبي"], ["maps", "قياس الخرائط"], ["imports", "استيراد قياس Google"]].map(([id, title]) => <button key={id} aria-pressed={tab === id} className={tab === id ? "active" : ""} onClick={() => { setTab(id); setError(""); setNotice(""); }}>{title}</button>)}</div>
    {notice && <p className="growth-notice" role="status">{notice}</p>}{error && <p className="crm-error" role="alert">{error} <button onClick={() => setRevision(n => n + 1)}>تحديث البيانات</button></p>}
    {loaded !== revision ? <p role="status">جارٍ تحميل سجل المركز…</p> : inventory && <>
      {tab === "content" && <section className="panel growth-panel"><div className="crm-panel-head"><div><span className="crm-section-kicker">معلومات مؤكدة قبل النشر</span><h2>الفحوص والفريق والمراجعة الطبية</h2><p>المسودة خاصة بالإدارة. الاعتماد يتطلب مرجعًا، اسم من أكد المعلومات، وتاريخ التأكيد.</p></div></div>
        <div className="growth-inventory">{services.map(s => { const entry = inventory.content.find(x => x.id === s.slug); return <button key={s.slug} onClick={() => choose("service", s.slug)}><strong>{s.shortTitle}</strong><span>{entry?.status === "approved" ? "معتمد" : entry ? "مسودة" : "بانتظار معلومات الفريق"}</span></button>; })}</div>
        <form className="crm-form" onSubmit={e => { e.preventDefault(); if (form.kind === "review" && form.status === "approved" && form.data.contentVersion !== blogPosts.find(p => `review-${p.slug}` === form.id)?.modified) { setError("حدد نسخة المقال الحالية التي تمت مراجعتها قبل الاعتماد."); return; } void save("growth_content_save", { ...form, attested }); }}>
          <fieldset disabled={busy} className="growth-fieldset">
            <label className="crm-field"><span>نوع السجل</span><select value={form.kind} onChange={e => { const kind = e.target.value as MedicalContent["kind"]; choose(kind, kind === "service" ? services[0].slug : kind === "review" ? `review-${article}` : `clinician-${crypto.randomUUID().slice(0, 8)}`); }}><option value="service">تفاصيل خدمة</option><option value="clinician">عضو الفريق الطبي</option><option value="review">مراجعة مقال فعلية</option></select></label>
            {form.kind === "service" ? <label className="crm-field"><span>صفحة الفحص</span><select value={form.id} onChange={e => choose("service", e.target.value)}>{services.map(s => <option key={s.slug} value={s.slug}>{s.shortTitle}</option>)}</select></label> : form.kind === "clinician" ? <label className="crm-field"><span>عضو الفريق</span><select value={form.version ? form.id : "new"} onChange={e => choose("clinician", e.target.value === "new" ? `clinician-${crypto.randomUUID().slice(0, 8)}` : e.target.value)}><option value="new">إضافة عضو</option>{inventory.content.filter(x => x.kind === "clinician").map(x => <option key={x.id} value={x.id}>{x.data.name || x.id}</option>)}</select></label> : <label className="crm-field"><span>المقال الذي تمت مراجعته</span><select value={form.id.replace(/^review-/, "")} onChange={e => { setArticle(e.target.value); choose("review", `review-${e.target.value}`); }}>{blogPosts.map(p => <option key={p.slug} value={p.slug}>{p.title}</option>)}</select></label>}
            {form.kind === "service" && <>{[["supportedExams", "الفحوص المتاحة فعليًا حسب الإحالة"], ["preparation", "تعليمات التحضير المعتمدة والفروق بين الفحوص"], ["reportProcess", "من يصدر التقرير وكيف ومتى تُسلّم الصور والنتيجة"], ["duration", "مدة الموعد إن كانت مؤكدة"]].map(([id, label]) => <label className="crm-field crm-full" key={id}><span>{label}</span><textarea rows={3} maxLength={id === "reportProcess" ? 1500 : id === "duration" ? 300 : 2000} value={form.data[id] || ""} onChange={e => field(id, e.target.value)} required={form.status === "approved" && id !== "duration"}/></label>)}<label className="crm-field crm-full"><span>صورة الجهاز الأصلية بعد تأكيد الفريق</span><select value={form.data.devicePhoto || ""} onChange={e => field("devicePhoto", e.target.value)}>{Object.entries(photos).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label></>}
            {form.kind === "clinician" && [["name", "الاسم المهني الموثّق"], ["specialty", "التخصص الموثّق"], ["qualification", "المؤهل أو التصنيف المهني المؤكد"]].map(([id, label]) => <label className="crm-field crm-full" key={id}><span>{label}</span><input value={form.data[id] || ""} maxLength={id === "name" ? 100 : id === "specialty" ? 150 : 200} required={form.status === "approved"} onChange={e => field(id, e.target.value)}/></label>)}
            {form.kind === "review" && <><label className="crm-field"><span>المراجع الطبي الموثّق</span><select value={form.data.reviewerId || ""} required={form.status === "approved"} onChange={e => field("reviewerId", e.target.value)}><option value="">اختر عضوًا معتمدًا</option>{clinicians.map(x => <option key={x.id} value={x.id}>{x.data.name} · {x.data.specialty}</option>)}</select></label><label className="crm-field"><span>تاريخ المراجعة الفعلية</span><input type="date" max={riyadhDay()} value={form.data.reviewedAt || ""} required={form.status === "approved"} onChange={e => field("reviewedAt", e.target.value)}/></label><label className="crm-field crm-full"><span>نسخة المقال التي تمت مراجعتها · تاريخ آخر تعديل</span><input type="date" value={form.data.contentVersion || ""} required={form.status === "approved"} onChange={e => field("contentVersion", e.target.value)}/><small>النسخة الحالية: {blogPosts.find(p => `review-${p.slug}` === form.id)?.modified}. اقرأ المقال كاملًا وسجل المراجعة الفعلية؛ تغيير نسخة المقال يلغي إظهار الاعتماد القديم.</small><a href={`/blog/${form.id.replace(/^review-/, "")}`} target="_blank" rel="noreferrer">افتح المقال للمراجعة</a></label></>}
            <label className="crm-field crm-full"><span>مرجع التأكيد أو المستند · خاص بالإدارة</span><textarea rows={2} maxLength={1000} required={form.status === "approved"} value={form.evidence} onChange={e => setForm(f => ({ ...f, evidence: e.target.value }))} placeholder="مرجع سجل مهني أو موافقة مكتوبة من الفريق؛ دون بيانات مرضى"/></label>
            <label className="crm-field"><span>اسم من أكد المعلومات</span><input maxLength={100} required={form.status === "approved"} value={form.confirmed_by} onChange={e => setForm(f => ({ ...f, confirmed_by: e.target.value }))}/></label><label className="crm-field"><span>تاريخ التأكيد</span><input type="date" max={riyadhDay()} required={form.status === "approved"} value={form.confirmed_at || ""} onChange={e => setForm(f => ({ ...f, confirmed_at: e.target.value }))}/></label>
            <label className="crm-field"><span>حالة النشر</span><select value={form.status} onChange={e => { setForm(f => ({ ...f, status: e.target.value as MedicalContent["status"] })); setAttested(false); }}><option value="draft">مسودة خاصة</option><option value="approved">اعتماد ونشر</option></select></label>
            {form.status === "approved" && <label className="growth-attestation crm-full"><input type="checkbox" required checked={attested} onChange={e => setAttested(e.target.checked)}/><span>أؤكد التحقق من المعلومات وموافقة الفريق على نشرها، أو إجراء المراجعة الطبية الفعلية للنسخة المحددة.</span></label>}
          </fieldset><div className="crm-dialog-actions crm-full"><button className="button primary" disabled={busy}>{busy ? "جارٍ الحفظ…" : form.status === "approved" ? "حفظ الاعتماد والنشر" : "حفظ المسودة"}</button></div>
        </form>
      </section>}
      {tab === "maps" && <section className="panel growth-panel"><div className="crm-panel-head"><div><span className="crm-section-kicker">المربع · الملز · العليا · السليمانية</span><h2>سجل قياس ترتيب الخرائط</h2><p>الترتيب مرتبط بنقطة وكلمة وجهاز ووقت. استخدم النقاط نفسها عند التكرار، وافصل الإعلان عن النتيجة المحلية.</p></div></div>
        <div className="growth-inventory">{neighborhoods.map(n => { const count = inventory.maps.filter(x => x.neighborhood === n).length; return <article key={n}><strong>{n}</strong><span>{count ? `${count} قياسًا موثّقًا` : "لم يُسجّل قياس فعلي بعد"}</span></article>; })}</div>
        <form className="crm-form" onSubmit={e => { e.preventDefault(); const d = Object.fromEntries(new FormData(e.currentTarget)); void save("growth_maps_save", { ...d, rank: rankResult === "outside" ? "" : d.rank, language: "ar", measured_at: new Date(`${d.measured_at}:00+03:00`).toISOString() }); }}><fieldset disabled={busy} className="growth-fieldset">
          <label className="crm-field"><span>الحي</span><select name="neighborhood">{neighborhoods.map(n => <option key={n}>{n}</option>)}</select></label><label className="crm-field"><span>اسم نقطة القياس الثابتة</span><input name="point_label" required minLength={2} maxLength={150} placeholder="اسم الموقع الذي أُجري منه القياس"/></label>
          <label className="crm-field"><span>خط العرض</span><input name="latitude" type="number" step="any" min="24.3" max="25" required dir="ltr"/></label><label className="crm-field"><span>خط الطول</span><input name="longitude" type="number" step="any" min="46.3" max="47.2" required dir="ltr"/></label>
          <label className="crm-field"><span>عبارة البحث بالحرف</span><input name="query" required minLength={3} maxLength={200} defaultValue="مركز أشعة بالرياض"/></label><label className="crm-field"><span>الجهاز · اللغة العربية</span><select name="device"><option value="mobile">جوال</option><option value="desktop">كمبيوتر</option></select></label>
          <label className="crm-field"><span>وقت القياس الفعلي · الرياض</span><input type="datetime-local" name="measured_at" required max={localInput()} defaultValue={localInput()}/></label><label className="crm-field"><span>عدد النتائج المفحوصة</span><input type="number" name="depth" min={3} max={100} required defaultValue={20}/></label>
          <label className="crm-field"><span>نتيجة المركز</span><select value={rankResult} onChange={e => setRankResult(e.target.value)}><option value="found">ظهر ضمن النتائج</option><option value="outside">لم يظهر ضمن العمق المفحوص</option></select></label>{rankResult === "found" && <label className="crm-field"><span>الترتيب المرصود دون الإعلانات</span><input name="rank" type="number" min={1} max={100} required/></label>}
          <label className="crm-field crm-full"><span>أداة القياس أو طريقة التحقق من موقع الباحث</span><input name="method" required minLength={3} maxLength={200} placeholder="أداة شبكة محلية، أو بحث من جهاز موجود فعليًا في النقطة"/></label><label className="crm-field crm-full"><span>رابط تقرير أو لقطة إثبات القياس</span><input type="url" name="evidence_url" required pattern="https://.*" maxLength={1000} placeholder="https://…" dir="ltr"/></label>
        </fieldset><button className="button primary" disabled={busy}>حفظ قياس فعلي</button></form>
        {inventory.maps.length > 0 && <div className="crm-table-wrap"><table className="crm-table"><thead><tr><th>الحي والنقطة</th><th>البحث</th><th>الترتيب</th><th>وقت القياس</th><th>الجهاز</th><th>الإثبات</th></tr></thead><tbody>{inventory.maps.map(x => <tr key={x.id}><td>{x.neighborhood} · {x.point_label}<small className="crm-cell-sub" dir="ltr">{x.latitude}, {x.longitude}</small></td><td>{x.query}</td><td>{x.rank ?? `خارج ${x.depth}`}</td><td>{displayDate(x.measured_at)}</td><td>{x.device === "mobile" ? "جوال" : "كمبيوتر"}</td><td><a href={x.evidence_url} target="_blank" rel="noreferrer">عرض الدليل</a><small className="crm-cell-sub">{x.method}</small></td></tr>)}</tbody></table></div>}
      </section>}
      {tab === "imports" && <section className="panel growth-panel"><h2>إضافة أسبوع Google مكتمل</h2><p>استورد الأرقام من الملف التجاري نفسه مع مرجع التصدير. لا تستخدم بيانات يوم غير مكتمل. نتائج CRM تُقرأ تلقائيًا للفترة نفسها في تقارير CRM.</p><form className="crm-form" onSubmit={e => { e.preventDefault(); const d = Object.fromEntries(new FormData(e.currentTarget)); void save("growth_gbp_save", { ...d, version: inventory.periods.find(p => p.date_from === d.date_from)?.version || 0 }); }}><fieldset disabled={busy} className="growth-fieldset">
        <label className="crm-field"><span>أول يوم</span><input type="date" name="date_from" required/></label><label className="crm-field"><span>آخر يوم · 7 أيام بالضبط</span><input type="date" name="date_to" max={riyadhDay()} required/></label>{[["calls", "ضغطات اتصال"], ["website", "نقرات الموقع"], ["directions", "طلبات الاتجاهات"]].map(([name, label]) => <label className="crm-field" key={name}><span>{label}</span><input type="number" name={name} min={0} step={1} required/></label>)}<label className="crm-field crm-full"><span>المصدر ومرجع الاستخراج</span><input name="source" required minLength={5} maxLength={500} placeholder="Google Business Profile · معرف الملف · رابط أو تاريخ تصدير التقرير"/></label></fieldset><button disabled={busy} className="button primary">حفظ فترة Google</button></form>
        <div className="crm-table-wrap"><table className="crm-table"><thead><tr><th>الفترة</th><th>ضغطات اتصال</th><th>نقرات الموقع</th><th>اتجاهات</th><th>المصدر</th></tr></thead><tbody>{inventory.periods.map(p => <tr key={p.date_from}><td>{p.date_from} – {p.date_to}</td><td>{p.calls}</td><td>{p.website}</td><td>{p.directions}</td><td>{p.source}<small className="crm-cell-sub">استيراد {displayDate(p.imported_at)}</small></td></tr>)}</tbody></table></div>
      </section>}
    </>}
  </div>;
}
